//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 02:03:45 PM EST 
//


package org.pentaho.agilebi.modeler.models.annotations.util;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FormatShortcutEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FormatShortcutEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NONE"/>
 *     &lt;enumeration value="COLOR_SCALE_G_Y_R"/>
 *     &lt;enumeration value="COLOR_SCALE_R_Y_G"/>
 *     &lt;enumeration value="COLOR_SCALE_B_Y_R"/>
 *     &lt;enumeration value="COLOR_SCALE_R_Y_B"/>
 *     &lt;enumeration value="TREND_ARROW_GR"/>
 *     &lt;enumeration value="TREND_ARROW_RG"/>
 *     &lt;enumeration value="DATA_BAR_RED"/>
 *     &lt;enumeration value="DATA_BAR_GREEN"/>
 *     &lt;enumeration value="DATA_BAR_BLUE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FormatShortcutEnum")
@XmlEnum
public enum FormatShortcutEnum {

    NONE,
    COLOR_SCALE_G_Y_R,
    COLOR_SCALE_R_Y_G,
    COLOR_SCALE_B_Y_R,
    COLOR_SCALE_R_Y_B,
    TREND_ARROW_GR,
    TREND_ARROW_RG,
    DATA_BAR_RED,
    DATA_BAR_GREEN,
    DATA_BAR_BLUE;

    public String value() {
        return name();
    }

    public static FormatShortcutEnum fromValue(String v) {
        return valueOf(v);
    }

}
