//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 02:03:45 PM EST 
//


package org.pentaho.agilebi.modeler.models.annotations.util;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FormatCategoryEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FormatCategoryEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Default"/>
 *     &lt;enumeration value="General Number"/>
 *     &lt;enumeration value="Currency ($)"/>
 *     &lt;enumeration value="Percentage (%)"/>
 *     &lt;enumeration value="Expression"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FormatCategoryEnum")
@XmlEnum
public enum FormatCategoryEnum {

    @XmlEnumValue("Default")
    DEFAULT("Default"),
    @XmlEnumValue("General Number")
    GENERAL_NUMBER("General Number"),
    @XmlEnumValue("Currency ($)")
    CURRENCY_$("Currency ($)"),
    @XmlEnumValue("Percentage (%)")
    PERCENTAGE("Percentage (%)"),
    @XmlEnumValue("Expression")
    EXPRESSION("Expression");
    private final String value;

    FormatCategoryEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FormatCategoryEnum fromValue(String v) {
        for (FormatCategoryEnum c: FormatCategoryEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
